= Þar sem villidýrin búa

Nóttina sem Max fór í úlfaham og ærslaðist á einn hátt

og annan

kallaði móðir hans hann "VILLIDÝR!" og Max sagði "ÉG ÉT ÞIG UPP
TIL AGNA!" svo hann var sendur í rúmið án þess að fá kvöldmat.

Þá sömu nótt spratt skógur í herbergi Max

og óx

og óx þar til loftið var viðjum þakið og veggirnir urðu veröldin
allt í kring

og haf brölti hjá með einkabát handa Max og hann sigldi burt gegnum
nótt og dag

og inn og út úr vikum og næstum yfir ár þangað sem að villidýrin
búa.

Og þegar hann kom þangað sem að villidýrin búa öskruðu þau
hræðilegum öskrum og gnístu hræðilegum tönnum og ranghvolfdu
hræðilegum augum og sýndu hræðilegar klær

þar til Max sagði "VERIÐ KYRR!" og tamdi þau með töfrandi störu
í gul augu þeirra án þess að blikka einu sinni og þau skelfdust
og kölluðu hann villtasta dýr þeirra allra

og krýndu hann kóng allra villta dýra.

"Og nú," hrópaði Max, "skal gauragangurinn hefjast!"

"Stopp!" sagði Max og sendi villidýrin í rúmið án þess að fá
kvöldmat. Og Max konungur allra villtra dýra var einmana og vildi að
hann væri þar sem einhver elskaði hann mest allra.

Þá, allt í kring, alla leið hinum megin úr veröldinni, fann hann
góða matarlykt svo hann afsalaði sér krúnu villtra dýra.

En villidýrin góluðu, "Ó nei, farðu ei -- við étum þig upp til
agna -- þú ert svo meyr!" Og Max sagði, "Nei!".

Villidýrin öskruðu hræðilegum öskrum og gnístu hræðilegum
tönnum og ranghvolfdu hræðilegum augum og sýndu hræðilegar klær
en Max steig um borð í einkabátinn sinn og kvaddi

og sigldi til baka yfir ár og inn og út úr vikum og gegnum dag

og inn í nóttina í herberginu sínu þar sem kvöldmaturinn beið hans

og hann var ennþá heitur.
